### PR TITLE
Add my theme

### PR DESCRIPTION
**Pull request by Ouraniasapphire**
Its really good. Base theme is Night by DaisyUI.

### CODE REVIEW

**Comment by MostlyBen** [comment]
You should follow the existing naming convention (all lower-case) and update the theme selector so it appears as an option in the dropdown

**Comment by Sapphired89** [comment]
Updated theme selector and name.

**Comment by MostlyBen** [comment]
Is it in alphabetical order like the rest of the themes?

**Comment by Ouraniasapphire** [comment]
Yes it is.

**Pull request merged**
